postgres:
  spring:
    datasource:
      jdbcUrl: jdbc:postgresql://localhost:5432/simple_spring
      username: postgres
      password: qwer1234
      maximumPoolSize: 10
      auto-commit: true
mssql:
  spring:
    datasource:
      jdbcUrl: jdbc:sqlserver://localhost
      username: sa
      password: tmdrms159@
      maximumPoolSize: 10
      port: 1433
      database: simple_procedures
