spring:
  datasource:
    jdbcUrl: jdbc:sqlserver://localhost
    database: simple_procedures
    port: 1433
    username: sa
    password: tmdrms159@
    maximumPoolSize: 10
    auto-commit: true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver